[tool:pytest]
testpaths = tests
python_files = test_*.py
pythonpath = 
  src
  .
python_classes = Test*
python_functions = test_*
addopts = -v --import-mode=importlib
dev_dependencies = true
