# scripts/fetch_models.py

"""Fetch available LLM models and save to .agent/llm.yaml."""

import argparse
import asyncio
import datetime
import sys
from pathlib import Path

import yaml

# Add src to path to allow imports
sys.path.append(str(Path(__file__).parents[1] / "src"))

# pylint: disable=wrong-import-position
from lib.webscrape import scrape_pricing
from llm.client import LLM_CLIENTS, OpenAIClient


class GroqClient(OpenAIClient):
    """Groq API."""

    base_url_default = "https://api.groq.com/openai/v1"
    pricing_url = ""


LLM_CLIENTS["Groq"] = GroqClient


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description="Fetch available LLM models.")
    parser.add_argument(
        "providers",
        nargs="*",
        help="List of providers to fetch (case-insensitive). Defaults to all.",
    )
    return parser.parse_args()


async def main() -> None:
    """Fetch models from configured providers."""
    args = parse_args()
    root_dir = Path(__file__).parents[1]
    agent_dir = root_dir / ".agent"
    secrets_path = agent_dir / "secrets.env.yaml"
    output_path = agent_dir / "llm.yaml"

    if not secrets_path.exists():
        print(f"❌ Secrets file not found: {secrets_path}")
        return

    def load_secrets() -> dict:
        with open(secrets_path, encoding="utf-8") as f:
            return yaml.safe_load(f) or {}

    secrets = await asyncio.to_thread(load_secrets)

    llm_secrets = secrets.get("llm", {})

    # Load existing data to preserve costs
    existing_data = {}
    if output_path.exists():

        def load_existing() -> dict:
            with open(output_path, encoding="utf-8") as f:
                return yaml.safe_load(f) or {}

        existing_data = await asyncio.to_thread(load_existing)

    # Prepare output structure
    output_data = existing_data.copy()

    clients_to_process = LLM_CLIENTS
    if args.providers:
        requested = {p.lower() for p in args.providers}
        clients_to_process = {k: v for k, v in LLM_CLIENTS.items() if k.lower() in requested}

        if not clients_to_process:
            print(f"❌ No matching providers found. Available: {list(LLM_CLIENTS.keys())}")
            return

    for title, client_cls in clients_to_process.items():
        name = title.lower().replace(" ", "_")

        # Ensure structure exists
        if name not in output_data:
            output_data[name] = {}
        if isinstance(output_data[name], list):
            output_data[name] = {"models": output_data[name]}

        # Update costs
        costs = {}
        if client_cls.pricing_url:
            print(f"  💰 Fetching pricing for {title}...")
            costs = await scrape_pricing(
                name,
                client_cls.pricing_url,
                selector=client_cls.pricing_selector,
                parse_hint=client_cls.pricing_hint,
            )
            if "costs" not in output_data[name]:
                output_data[name]["costs"] = {}
            output_data[name]["costs"].update(costs)
            output_data[name]["last_updated"] = datetime.date.today().isoformat()

        # Fetch models
        models = []
        if (secret := llm_secrets.get(name)) and secret.get("api_key"):
            print(f"Fetching {title} models...")
            client = client_cls(
                api_key=secret["api_key"],
                base_url=secret.get("api_base", ""),
                model="dummy",
            )
            try:
                models = await client.list_models()
                print(f"  ✅ Found {len(models)} models")
            except Exception as e:  # pylint: disable=broad-exception-caught
                print(f"  ❌ Failed: {e}")
            finally:
                await client.close()

        if not models and costs:
            print(f"  ⚠️  Using {len(costs)} models from pricing page.")
            models = list(costs.keys())

        if models:
            output_data[name]["models"] = sorted(models)

    if output_data:

        def save_models() -> None:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(f"# Auto-generated by scripts/fetch_models.py on {datetime.date.today()}\n")
                yaml.safe_dump(output_data, f)

        await asyncio.to_thread(save_models)
        print(f"💾 Saved models to {output_path}")
    else:
        print("⚠️  No models fetched.")


if __name__ == "__main__":
    asyncio.run(main())
