# src/agent/lib/models.py

"""Model fetching and validation logic."""

from __future__ import annotations

import asyncio
import datetime
from pathlib import Path
from typing import Any

import yaml

from lib.webscrape import scrape_pricing
from llm.client import LLM_CLIENTS, OpenAIClient


class GroqClient(OpenAIClient):
    """Groq API."""

    base_url_default = "https://api.groq.com/openai/v1"
    pricing_url = ""


# Register Groq
LLM_CLIENTS["Groq"] = GroqClient


async def fetch_and_save_models(secrets: dict[str, Any], output_path: Path, log_func: Any = print) -> bool:
    """Fetch models using provided secrets and save to output_path."""
    llm_secrets = secrets.get("llm", {})

    # Load existing data to preserve costs if file exists
    existing_data: dict[str, Any] = {}
    if output_path.exists():
        try:

            def _load() -> dict[str, Any]:
                with open(output_path, encoding="utf-8") as f:
                    return yaml.safe_load(f) or {}

            existing_data = await asyncio.to_thread(_load)
        except Exception:  # pylint: disable=broad-exception-caught
            pass

    output_data = existing_data.copy()
    success = False

    for title, client_cls in LLM_CLIENTS.items():
        name = title.lower().replace(" ", "_")

        # Ensure structure
        if name in output_data and isinstance(output_data[name], list):
            output_data[name] = {"models": output_data[name]}

        # Fetch models if we have a key
        secret = llm_secrets.get(name)
        if secret and secret.get("api_key"):
            log_func(f"  Testing {title} API...")
            client = client_cls(
                api_key=secret["api_key"],
                base_url=secret.get("api_base", ""),
                model="dummy",
            )
            try:
                models = await client.list_models()
                if models:
                    output_data.setdefault(name, {})["models"] = sorted(models)
                    success = True
                    log_func(f"    ✅ Verified {title} ({len(models)} models)")
                else:
                    log_func(f"    ⚠️  Connected to {title} but found no models.")
            except Exception as e:  # pylint: disable=broad-exception-caught
                log_func(f"    ❌ {title} check failed: {e}")
            finally:
                await client.close()

        # Pricing scrape (opportunistic)
        if client_cls.pricing_url and "costs" not in output_data.get(name, {}):
            # We skip detailed logging for pricing to keep wizard fast
            try:
                costs = await scrape_pricing(
                    name,
                    client_cls.pricing_url,
                    selector=client_cls.pricing_selector,
                    parse_hint=client_cls.pricing_hint,
                )
                if costs:
                    entry = output_data.setdefault(name, {})
                    entry.setdefault("costs", {}).update(costs)
                    entry["last_updated"] = datetime.date.today().isoformat()
            except Exception:  # pylint: disable=broad-exception-caught
                pass

    if success or output_data:

        def _save() -> None:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(f"# Auto-generated by Blondie Wizard on {datetime.date.today()}\n")
                yaml.safe_dump(output_data, f)

        await asyncio.to_thread(_save)
        return True

    return False
